AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for creating the crh-be-executor-bb IAM Role

Resources:
  CRHBEExecutorBBRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: crh-be-executor-bb
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole